### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by nessus42** [cursive-ide/emacs-plus#17]
I notice that there hasn't been a commit in nearly two years, and I'm now getting errors in IntelliJ that are being blamed on this plugin.

Alas, Emacs has been hardwired into my fingers and brain for decades, and I don't think I can change. I am afraid!

I've noticed that there is a new Emacs Keymap plugin from JetBrains in the Intellij Plugin Marketplace, but Google does not reveal whether anyone actually uses it and likes it. And there are no reviews of it on the page for it in the Marketplace.

Well, thank you to whoever made this decompiled plugin happen. It saved me from at least a couple years of endless torment.

**Comment by cursive-ghost** [comment]
It's not dead, but it's mostly unmaintained. I don't use it myself, and I initially created it as a service to the users of my other project (Cursive, a Clojure IDE). If someone would like to take this over I'd be most happy, and could provide guidance to the IntelliJ APIs. Otherwise I'll try to keep it up to date in my spare time, but no promises.

This plugin has essentially no tests, so if anything doesn't work as expected let me know and I'll see if I can find some time to create some test cases. I've only done rudimentary testing on this latest release, the error everyone seemed to be hitting is fixed but I don't know if anything else has broken.

**Comment by nessus42** [comment]
Well, thanks so much for all the work you did put into this, and for your recent fix!

**Comment by cursive-ghost** [comment]
No problem, let me know if you find issues with it and I'll try to create some test cases.

**Comment by nessus42** [comment]
Will do!
